name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

env:
  ZIG_VERSION: 0.13.0

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: false
      - name: Run check
        run: zig build check
      - name: Check formatting
        run: zig fmt --check .
      - name: Check readme
        run: |
          zig build readme
          git diff --exit-code -- README.md
      - name: Run unit tests
        run: zig build test
      - name: Run example tests
        run: zig build example
