name: checks

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: latest
          use-cache: false
      - name: Run check
        run: zig build check
      - name: Check formatting
        run: zig fmt --check .
      - name: Check readme
        run: |
          zig build readme
          git diff --exit-code -- README.md

  unit-tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig: [latest]
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig }}
          use-cache: false
      - name: Run tests
        run: zig build test -Doptimize=${{ matrix.optimize }}
      - name: Run example tests
        run: zig build example -Doptimize=${{ matrix.optimize }}
